### ISSUE TITLE
[Patch Request]:Rimatomics

### ISSUE THREAD

**Issue by sealvessel** [CombatExtended-Continued/CombatExtended#118]
**Title should be:** [Patch Request]: (Mod Name)

**Mod name:Rimatomics**

**Link to mod download (preferably Steam workshop or Github): https://github.com/Dubwise56/Rimatomics**

**Description:**
The turrets in rimatomics when with combat extended have no armor penetration mechanic. A few marauders(turrets which rapidly shoot explosives) can't dent a centipede. The marauder turret, punisher, tesla coil, and obelisk need fixes to armor penetration. 

**Content:**
What does the new mod contain? Check all that apply.
- [x] New weapons.
- [ ] New animals, humanoids, or other creatures.
- [ ] New factions.
- [x] New armor or apparel.

**Complete the following checklist before submitting a request.**
I hereby verify that I have done all of the following:
- [x] Searched the Steam workshop, Discord, and Github for an existing patch and not found one.
- [x] Confirmed there are no other open Patch Requests for this mod.
- [x] Confirmed the requested mod is not known to be fundamentally incompatible with Combat Extended.
- [x] **Have completed this template accurately and completely.**
- [x] **Understand that putting in a Patch Request does not guarantee a patch will be made.**
- [x] **Agree that I will not directly contact contributors to ask about patch requests.**

**Putting in request does not guarantee a patch will be made. Do not directly contact team members about Patch Requests. For smaller mods, consider reviewing the guide and making a patch yourself. If you wish to create a patch for any requested mod, there is no need to ask for permission.**

**Comment by exuvo** [comment]
There is also the energy weapon shield upgrade (SCAD) which might need patching, ill give it a try later and see if it works already. The HAL anti mortar might also have problems with CE mortar shells.

The tesla coil and obelisk do damage to things but i suspect they just ignore armor completely. Honestly for me it is fine if the tesla ignores armor as it is an unconventional weapon with short range. Tesla coil stun also works.

**Comment by skycrossercat** [comment]
The shield actually provides damage reduction iirc, and in my playthrough before, HEL can take down mortar shells and even more effective than in vanilla since CE's mortar shells fly in a very high, slow curve. Can confirm the tesla and obelisk's ignore armor part, and the stun from tesla coil can do electrical burn to mechs iirc. 
Armors are easy to patch, they don't really provide enough armor because they just made in cloth. Biggest problems are marauder and punisher, they use turret definition different from vanilla one, but CE can adapt vanilla's bomb damage right now, you can try increasing their damage and see if they're effective with the change in CE.

**Comment by Kazzerk** [comment]
the mod has a new energy shield to block bullets, it works fine without CE but with CE doesn't stop anything, the name of the shield is sentinel.

**Comment by exuvo** [comment]
Looks like @ItsSamGray fixed the turrets while @perkinslr fixed the shield, €5 each then? Send me SEPA info or paypal account name to exuvo@exuvo.se if you want the money.
