### ISSUE TITLE
[Bug]: Ranged weapons no longer shoot

### ISSUE THREAD

**Issue by WSeegers** [CombatExtended-Continued/CombatExtended#1225]
Rimworld version: 1.3.3200
Combat Extended version: 1.3.4.4
Combat Extended source (Steam, GitHub, etc.): Steam
Your operating system: Windows
Your mod list: Harmony, Core, Ideology, Royalty, Combat Extended (Loaded in order)

**Description**
Ranged weapons are not shooting. This happens both when drafted and when prioritizing hunting. It also seems like hunters do no longer hunt if they have a ranged weapon.

**Expected behavior**
Ranged weapons should shoot.

**To reproduce**
Start a crash landed scenario, equip ranged weapon, pickup ammo, reload, draft and attempt to shoot anything, 

**Screenshots & log dumps**
Nothing to show.

**Complete the following checklist**
I hereby verify that I have done the following:
- [x] Confirmed that my game version and load order are correct.
- [x] Confirmed that I am running the appropriate and most updated version of Combat Extended and required compatibility patches.
- [x] Confirmed I am not running any mods with known incompatibilities with Combat Extended.
- [x] Disabled Combat Extended and attempted to reproduce the behavior without success.

**Comment by perkinslr** [comment]
This is likely due to a phantom dependency on VFE-security.  It has been fixed, and was the reason for the hotfix late sunday/early monday (Pacific time).  Unforunately, some people have had difficulties getting steam to fetch the hotfixed version.  If it is still happening, you can unsubscribe/resubscribe and that *should* force steam to get the correct version.  

If the problem persists, please let us know.

**Comment by WSeegers** [comment]
The patch did indeed solve the issue. Thank you.
