### ISSUE TITLE
[Patch Request]: [1.4] Ambition of the Cosmic

### ISSUE THREAD

**Issue by TheLoneDrow** [CombatExtended-Continued/CombatExtended#2292]
**Mod name: [1.4] Ambition of the Cosmic**

**Link to mod download:** https://steamcommunity.com/workshop/filedetails/?id=1802857253

**Description:**
This mod adds pretty overpowered guns and armor for ridiculous tech costs and material cost. I do think that mod needs patching for armors and guns (which are pretty op). If it would help there is a patch for RimWorld 1.3 but it does not work (I have tested). 
Link to the patch for 1.3:https://steamcommunity.com/sharedfiles/filedetails/?id=2298661324

**Content:**
What does the new mod contain? Check all that apply.
- [x] New weapons.
- [ ] New animals, humanoids, or other creatures.
- [ ] New factions.
- [x] New armor or apparel.

**Complete the following checklist before submitting a request.**
I hereby verify that I have done all of the following:
- [x] Searched the Steam workshop, Discord, and Github for an existing patch and not found one.
- [x] Confirmed there are no other open Patch Requests for this mod.
- [x] Confirmed the requested mod is not known to be fundamentally incompatible with Combat Extended.
- [x] **Have completed this template accurately and completely.**
- [x] **Understand that putting in a Patch Request does not guarantee a patch will be made.**
- [x] **Agree that I will not directly contact contributors to ask about patch requests.**

**Comment by SeruseThor** [comment]
Another AOTC user here, the mod Ambition of the Cosmic got renamed which is why the 1.3 patch stopped working. The 1.3 patch still works, but you'll need to open some files to update the mod name as a temporary fix. Manually renaming the mod to <li>Ambition of the Cosmic</li> in "!A_Patch_SNS_CE_Apparel.xml", "!A_Patch_SNS_CE_Guns.xml", and "!A_Patch_SNS_CE_Turrets.xml" will get it working, besides the known issues in the steam workshop description.
