### ISSUE TITLE
[Patch Request]: SaveOurShip2Experimental (Turrets Patch)

### ISSUE THREAD

**Issue by IDKCRI** [CombatExtended-Continued/CombatExtended#2645]
[Patch Request]: SaveOurShip2Experimental

**Mod name: SaveOurShip2Experimental**

**Link to mod download (preferably Steam workshop or Github):* https://github.com/SonicTHI/SaveOurShip2Experimental*

**Description:**
SoS2Experimental and CE is ones of favorite mods for many people and mostly work just fine together regardless of minor incomatability. But SoS2Experimental combat system (turrets specifically) is currently kinda buggy when it comes to planetside or in map battles and also do not have patch to utilize CE ammo and projectile systems. Maybe it's possible to make ongoing patch to test CE and SoS2 1.4 further compatability in terms of dev branches?

**Content:**
- [x] New weapons.
- [x] New animals, humanoids, or other creatures.
- [ ] New factions.
- [x] New armor or apparel.

**Complete the following checklist before submitting a request.**
I hereby verify that I have done all of the following:
- [x] Searched the Steam workshop, Discord, and Github for an existing patch and not found one.
- [x] Confirmed there are no other open Patch Requests for this mod.
- [x] Confirmed the requested mod is not known to be fundamentally incompatible with Combat Extended.
- [x] **Have completed this template accurately and completely.**
- [x] **Understand that putting in a Patch Request does not guarantee a patch will be made.**
- [x] **Agree that I will not directly contact contributors to ask about patch requests.**

**Comment by perkinslr** [comment]
There's no meaningful patch for most of SOS2's turrets.  Most of them just use energy to fire, and shooting between maps can't really make use of our ballistic system.  That said, there is some room for improvements.

1.  The on-map turrets need to fire properly.  Much like Rimatomics's punisher, they probably don't need to use our ballistic system, since they are capable of firing for *miles* without a significant accuracy issue, so the spread and sway at on-map distances is going to be fractions of a cell.  Darkness and smoke might matter, but that's about it.  
2. The cannon turrets that use uranium could be made to take dedicated shells.  If we do that, they should probably be given multiple ammo types like other high calibers, and will require a new shell.  I don't think this is really necessary, but would be a "nice to have".
3. The damage from SOS2 weapons against pawns currently has 0 sharp pen, and only has blunt pen based on being an explosive.  They probably *should* get their own values so they work properly with our armor system.  Against most pawns, the raw damage is high enough to not practically matter, but when VF vehicles get involved, it will.
