### ISSUE TITLE
[Patch Request]: New Alpha Animals 

### ISSUE THREAD

**Issue by feeddanoob** [CombatExtended-Continued/CombatExtended#580]
**Read and complete the template below. Requests that fail to follow the template will be deleted without warning.**

**If a Patch Request (open or closed) already exists for the same mod, you may add a reaction to indicate your support. Do not create another request. Duplicate requests will be deleted.**

**Title should be:** [Patch Request]: Alpha Animals
**Mod name:** Alpha Animals

**Link to mod download (preferably Steam workshop or Github):** https://steamcommunity.com/sharedfiles/filedetails/?id=1541721856

**Description:**
An update to the the alpha animals patch to include the new animals: Anima Colossus, Grey-Coated Mouflon, Thunderbeast, Erin, Crescendo Anole and Crystaline Caracal.

**Content:**
What does the new mod contain? Check all that apply.
- [ ] New weapons.
- [x] New animals, humanoids, or other creatures.
- [ ] New factions.
- [ ] New armor or apparel.

**Complete the following checklist before submitting a request.**
I hereby verify that I have done all of the following:
- [x] Searched the Steam workshop, Discord, and Github for an existing patch and not found one.
- [x] Confirmed there are no other open Patch Requests for this mod.
- [x] Confirmed the requested mod is not known to be fundamentally incompatible with Combat Extended.
- [x] **Have completed this template accurately and completely.**
- [x] **Understand that putting in a Patch Request does not guarantee a patch will be made.**
- [x] **Agree that I will not directly contact contributors to ask about patch requests.**

**Putting in request does not guarantee a patch will be made. Do not directly contact team members about Patch Requests. For smaller mods, consider reviewing the guide and making a patch yourself. If you wish to create a patch for any requested mod, there is no need to ask for permission.**

**Comment by feeddanoob** [comment]
Also how do you guys make patches for other mods to have CE compatibility.

**Comment by randomtyper** [comment]
Create a fork of this repository via github, create a branch in your fork (so you can update the fork). Then, just create and/or edit xml files using other patch xml files as templates. Try with anima colossus first, it should be the easiest one, because patch for Alpha Animals already contains xml patches for two colossus variants. If anima colossus has different from other colossi stats - no problem, just look into differences between vanilla versions, read stats guidelines in the wiki tab in the original repository of mod (open it and look at the tight side of the screen, they should be there) and quesstimate the stats following data you got. Then you can create a pull request (you can mark it as a draft, if you want) (after adding/editing xml file) into the main repository. After that, you can continue to work on your fork (do not create a pull request for each change, just edit your fork) while your changes will be reviewed. When you will be done and all stats will be reasonable, N7Huntsman or someone with enough authority will merge your branch into main mod.

**Comment by feeddanoob** [comment]
yeah...I'm still not sure I tried onto the projectiles (AA_AcidicVomit) but I was getting an error at startup with [Combat Extended] Patch operation Verse.PatchOperationFindMod(Alpha Animals) failed.

**Comment by randomtyper** [comment]
Just create a pull request and let me look into the changes. If I won't be able to help, then at least someone other will be able to see it.

**Comment by feeddanoob** [comment]
Okay so i fixed the issue on the projectile (was not a thingdef but vfes own thing...) I'll have the PR soonish.

**Comment by N7Huntsman** [comment]
Closed by #587 .
