### ISSUE TITLE
[Discussion]: Cover makes a pawn less survivable + Called shot

### ISSUE THREAD

**Issue by Breadbox2k19** [CombatExtended-Continued/CombatExtended#754]
Issue: 
Due to pawns always aiming for the center of mass, it is nearly impossible for a pawn with high shoot to hit anything but the torso with a non-automatic weapon against targets in the open. This mean no possibility of head shot even if the head is unprotected and the torso heavily armored.

On the other head, when taking cover, the target pawn will be instantly shot in the unprotected head as the shooter will be aiming for the head as it is the primary exposed bodypart. This means that pawns are safer without cover than with cover in many situations.

The higher the shooting of the pawns and lower the distance of engagement, the worse the worse gets.

Solution: 
I'm just throwing out idea here:
1)Reduce the width or length of the head and neck. Makes it harder for head shot to be scored.
Increase the height of the torso, make it so that torso shot can be scored even when behind cover, this inturns reduces the near inevitability of headshots when behind cover.

2)Add heashot mode to certain weapon(snipers), allow them to specifically target the head or other small, vulnerable bodyparts.
This also have the effect of making sniper rifles not so goddamn useless.

**Comment by Arcalane** [comment]
In my experience, the main vulnerability for pawns behind cover is not the head but the neck. It rarely has good armour values (unsurprisingly) and isn't particularly durable. The vast majority of my combat losses have been people's necks getting taken out by centipede charge blasters to the point that it's uncanny, like they have neck-seeking bullets.

I don't know if height or exposed parts change with firing stance, but if it does, this could provide another lever for balance; suppress offers the best cover but obviously has the lowest accuracy (the pawn exposes as little of themselves as possible, essentially blindfiring) whilst aim offers the best chance to hit but also the greatest risk of being hit by return fire.

Headshot mode would be nice. For snipers, the aim modes could be "head/torso/disable" rather than "aim/snap/suppress", where 'disable' has the sniping pawn try to hit an arm or leg for disabling purposes rather than aiming to outright kill.
